USE cs304;

INSERT INTO User (emailAddress, firstName, lastName, passwordHash, isAdmin, twoFactorPhoneNumber) VALUES ("a", "Bob", "Joe", "b", 1, "6041234567");
INSERT INTO `Organization` (`name`, `createdTimestamp`, `contactEmailAddress`) VALUES ('Macrohard', '2018-11-15 15:32:50', 'a');
INSERT INTO `Organization` (`name`, `createdTimestamp`, `contactEmailAddress`) VALUES ('test', '2018-11-15 18:28:01', 'a');
INSERT INTO `Organization` (`name`, `createdTimestamp`, `contactEmailAddress`) VALUES ('test2', '2018-11-15 18:34:37', 'a');
INSERT INTO `Organization` (`name`, `createdTimestamp`, `contactEmailAddress`) VALUES ('asd', '2018-11-15 18:35:50', 'a');
INSERT INTO `Organization` (`name`, `createdTimestamp`, `contactEmailAddress`) VALUES ('asdsad', '2018-11-15 18:37:26', 'a');
INSERT INTO `Organization` (`name`, `createdTimestamp`, `contactEmailAddress`) VALUES ('asdasf', '2018-11-15 20:20:08', 'a');
INSERT INTO `UserOrganizationPairs` (`organizationName`, `userEmailAddress`) VALUES ('asdasf', 'a');
INSERT INTO `UserOrganizationPairs` (`organizationName`, `userEmailAddress`) VALUES ('Macrohard', 'a');
INSERT INTO `Service` (`name`, `description`, `isPreview`, `isEnabled`, `isVirtualMachineService`, `imageUrl`) VALUES ('EC2', 'This is some cool stuff', 0, 1, 1, "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/AWS_Simple_Icons_Compute_Amazon_EC2_Instances.svg/300px-AWS_Simple_Icons_Compute_Amazon_EC2_Instances.svg.png");
INSERT INTO `Service` (`name`, `description`, `isPreview`, `isEnabled`, `isVirtualMachineService`, `imageUrl`) VALUES ('S3', 'ASdasdasd', 0, 1, 0, "https://sylvainleroy.com/wp-content/uploads/2018/02/s3.png");
INSERT INTO `Service` (`name`, `description`, `isPreview`, `isEnabled`, `isVirtualMachineService`, `imageUrl`) VALUES ('Compute', 'asdasdasd', 1, 1, 0, "https://www.stratoscale.com/wp-content/uploads/AWS-Lambda.png");
INSERT INTO `BaseImage` (`os`, `version`) VALUES ('Ubuntu', '14.03');
INSERT INTO `Region` (`name`) VALUES ('us-west');
INSERT INTO `VirtualMachine` (`description`, `ipAddress`, `state`, `cores`, `diskSpace`, `ram`, `baseImageOs`, `baseImageVersion`, `regionName`, `organizationName`, `virtualMachineServiceName`) VALUES ('Nobody toucha mah spaghet!', '0.0.0.0', 1, 2, 3, 4, 'Ubuntu', '14.03', 'us-west', 'Macrohard', 'S3');
INSERT INTO `ServiceInstance` (`name`, `regionName`, `serviceName`, `organizationName`) VALUES ('s1', 'us-west', 'S3', 'Macrohard');
INSERT INTO `ServiceInstanceKey` (`keyValue`, `activeUntil`, `serviceInstanceName`, `serviceInstanceServiceName`, `serviceInstanceOrganizationName`) VALUES ('asfas123213', '2018-11-16 17:48:49', 's1', 'S3', 'Macrohard');
INSERT INTO `ServiceInstanceConfiguration` (`configKey`, `serviceInstanceName`, `serviceInstanceServiceName`, `serviceInstanceOrganizationName`, `data`) VALUES ('PORT', 's1', 'S3', 'Macrohard', '8080');
INSERT INTO `AccessGroup` (`name`, `organizationName`) VALUES ('Admins', 'Macrohard');
INSERT INTO `AccessGroup` (`name`, `organizationName`) VALUES ('Merp', 'Macrohard');
INSERT INTO `AccessGroup` (`name`, `organizationName`) VALUES ('Testers', 'Macrohard');
INSERT INTO `UserAccessGroupPairs` (`accessGroupName`, `accessGroupOrganizationName`, `userEmailAddress`) VALUES ('Admins', 'Macrohard', 'a');
INSERT INTO `UserAccessGroupPairs` (`accessGroupName`, `accessGroupOrganizationName`, `userEmailAddress`) VALUES ('Testers', 'Macrohard', 'a');
INSERT INTO `UserAccessGroupPairs` (`accessGroupName`, `accessGroupOrganizationName`, `userEmailAddress`) VALUES ('Admins', 'Macrohard', 'test5@email.com');
INSERT INTO `ServiceSubscriptionTransaction` (`type`, `serviceName`, `organizationName`, `description`, `activeuntil`, `transactionNumber`, `amountPaid`, `processedTimestamp`) VALUES (1,'EC2','Macrohard','paul trolling','2020-01-01 00:00:01',1,999,NOW());
INSERT INTO `ServiceSubscriptionTransaction` (`type`, `serviceName`, `organizationName`, `description`, `activeuntil`, `transactionNumber`, `amountPaid`, `processedTimestamp`) VALUES (1,'S3','Macrohard','paul trolling','2017-01-01 00:00:01',1,999,'2016-07-01 00:00:01');
INSERT INTO `CreditCard` (`cardNumber`, `cvc`, `expiryDate`, `cardType`) VALUE ('5555111122224444', '321', NOW(), 505);
INSERT INTO `OrganizationCreditCardPairs` (`organizationName`, `creditCardNumber`) VALUES ('MacroHard', '5555111122224444');
